name: ismb2019
channels:
  - conda-forge
  - rmg
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - py3dmol
